create database retail_store;
use retail_store;

select*from customers;
select*from products;
select*from sales;

SELECT COUNT(*) FROM customers;

SELECT COUNT(DISTINCT customer_id) FROM sales;

SELECT COUNT(*) AS orphan_rows
FROM sales s
LEFT JOIN customers c
  ON s.customer_id = c.customer_id
WHERE c.customer_id IS NULL;     

SELECT DISTINCT s.customer_id
FROM sales s
LEFT JOIN customers c
  ON s.customer_id = c.customer_id
WHERE c.customer_id IS NULL;

SELECT customer_id, COUNT(*) AS cnt
FROM customers
GROUP BY customer_id
HAVING COUNT(*) > 1;

INSERT INTO customers (customer_id)
SELECT DISTINCT s.customer_id
FROM sales s
LEFT JOIN customers c
  ON s.customer_id = c.customer_id
WHERE c.customer_id IS NULL;

SELECT COUNT(*)
FROM sales s
LEFT JOIN customers c
  ON s.customer_id = c.customer_id
WHERE c.customer_id IS NULL;

ALTER TABLE sales
ADD CONSTRAINT fk_sales_customers
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id);


select*from customers; 
select*from products;
select*from sales;


-- LEVEL 1 — FOUNDATIONAL BUSINESS QUESTIONS
-- What is the total revenue generated by the company?
SELECT ROUND(SUM(unit_price * quantity), 2) AS Total_Revenue FROM sales ;
-- total revenue : 261334.96

-- How does revenue vary by product category?
SELECT p.category,ROUND(SUM(s.unit_price * s.quantity), 2) AS Total_Revenue FROM products AS p
INNER JOIN sales AS s ON p.product_id = s.product_id GROUP BY p.category;

-- category_revenue/total_revenue * 100
SELECT p.category, SUM(s.unit_price*s.quantity) AS category_revenue, 
(SUM(s.unit_price*s.quantity) / SUM(SUM(s.unit_price*s.quantity)) OVER()) * 100 AS pct_of_total FROM products as p 
inner join sales as s on p.product_id=s.product_id GROUP BY category;


-- Which products sell the highest number of units?
SELECT p.product_name,SUM(s.quantity) AS total_units_sold FROM sales s
INNER JOIN products p ON s.product_id = p.product_id GROUP BY p.product_name ORDER BY total_units_sold DESC;

-- What are the top-performing regions by revenue?
SELECT TRIM(region) as region, SUM(unit_price * quantity) AS Revenue FROM sales GROUP BY TRIM(region) ORDER BY Revenue DESC; 

-- How does revenue differ across payment methods?
select payment_method,sum(unit_price*quantity) as Revenue from sales group by payment_method ;

-- level2 : CUSTOMER & BEHAVIOR ANALYSIS
-- How many unique customers have placed orders?
select count(distinct customer_id) as unique_customers from sales;

-- Which customers have placed more than one order?
SELECT customer_id, COUNT(*) AS orders_placed FROM sales GROUP BY customer_id HAVING COUNT(*) > 1;

-- How does average order value differ by loyalty tier?
-- metric: AOV=total_revenue/no.of orders
WITH order_revenue AS (SELECT order_id, SUM(unit_price * quantity) AS order_total 
FROM sales GROUP BY order_id)
SELECT COALESCE(c.loyalty_tier,'Unknown') AS loyalty_tier,ROUND(AVG(order_total),2) AS avg_order_value FROM order_revenue o
LEFT JOIN sales s ON o.order_id = s.order_id
LEFT JOIN customers c ON s.customer_id = c.customer_id GROUP BY loyalty_tier;

-- Do customers in higher loyalty tiers generate more revenue per customer?
SELECT COALESCE(c.loyalty_tier,"Unknown") as loyalty_tier,
ROUND(SUM(s.unit_price * s.quantity) / COUNT(DISTINCT s.customer_id), 2) AS revenue_per_customer
FROM sales s INNER JOIN customers c ON s.customer_id = c.customer_id GROUP BY c.loyalty_tier ORDER BY revenue_per_customer DESC ;

-- What percentage of total revenue comes from repeat customers?
-- metric : (revenue_per_repeat_customers/total_revenue)*100
WITH total_revenue AS (
SELECT SUM(unit_price * quantity) AS total_rev FROM sales),  -- Total revenue
repeat_customers AS (      
SELECT customer_id FROM sales           -- Customers with more than one order
GROUP BY customer_id HAVING COUNT(DISTINCT order_id) > 1),
repeat_revenue AS (SELECT SUM(s.unit_price * s.quantity) AS repeat_rev FROM sales s  -- Revenue from repeat customers
JOIN repeat_customers r ON s.customer_id = r.customer_id)
SELECT ROUND((repeat_rev / total_rev) * 100, 2) AS repeat_customer_revenue_percentage  -- Final percentage
FROM total_revenue, repeat_revenue;

-- LEVEL 3 — DISCOUNTS, OPERATIONS & CONDITIONAL ANALYSIS
-- Compare revenue generated from discounted vs non-discounted orders.
SELECT CASE WHEN discount_applied > 0 THEN 'Discounted Orders' ELSE 'Non-Discounted Orders'
END AS order_type,ROUND(SUM(unit_price * quantity), 2) AS total_revenue
FROM sales GROUP BY order_type;

-- Is there a difference in average quantity purchased when a discount is applied?
SELECT CASE WHEN discount_applied > 0 THEN 'Discount Applied' ELSE 'No Discount'
END AS discount_status,ROUND(AVG(quantity), 2) AS avg_quantity
FROM sales GROUP BY discount_status;

-- Which regions respond better to discounts?
SELECT TRIM(region) AS region,COUNT(*) AS discounted_orders,ROUND(SUM(unit_price * quantity), 2) AS discounted_revenue,
ROUND(AVG(unit_price * quantity), 2) AS avg_discounted_order_value FROM sales WHERE discount_applied > 0
GROUP BY TRIM(region) ORDER BY discounted_revenue DESC;

-- Does delivery status (Delivered vs Cancelled) affect revenue contribution?
select delivery_status,sum(unit_price*quantity) as total_revenue from sales where delivery_status in('Delivered','Cancelled')
group by delivery_status;

-- Which payment methods have higher cancellation rates?
SELECT payment_method,ROUND(SUM(CASE WHEN delivery_status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS cancellation_rate_pct
FROM sales GROUP BY payment_method ORDER BY cancellation_rate_pct DESC;

-- LEVEL 4 — ADVANCED PRODUCT PERFORMANCE
-- Which products generate above-average revenue compared to all products?
WITH product_revenue AS (
SELECT p.product_id,p.product_name,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_id, p.product_name)
SELECT * FROM product_revenue WHERE revenue > (SELECT AVG(revenue) FROM product_revenue) ORDER BY revenue DESC;

-- Which products contribute to the top 80% of total revenue? (pareto analysis)
WITH product_revenue AS (SELECT p.product_name,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name),
ranked_products AS (SELECT product_name,revenue,SUM(revenue)
 OVER (ORDER BY revenue DESC) /SUM(revenue) OVER () AS cumulative_pct
FROM product_revenue)
SELECT * FROM ranked_products WHERE cumulative_pct <= 0.8;

 
-- top 20% products : 
WITH product_revenue AS (SELECT p.product_name,SUM(s.unit_price * s.quantity) AS revenue
FROM products p INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name),
ranked_products AS (SELECT product_name,revenue,
SUM(revenue) OVER (ORDER BY revenue DESC) / SUM(revenue) OVER () AS cumulative_pct FROM product_revenue)
SELECT * FROM ranked_products WHERE cumulative_pct <= 0.20 ORDER BY revenue DESC;

-- Are newer products (based on launch date) performing better than older ones?
SELECT CASE WHEN launch_date >= DATE_SUB(CURDATE(), INTERVAL 12 MONTH) THEN 'New Products' ELSE 'Older Products'
END AS product_age_group,ROUND(SUM(s.unit_price * s.quantity), 2) AS total_revenue,
ROUND(AVG(s.unit_price * s.quantity), 2) AS avg_order_revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY product_age_group;

-- Which suppliers are associated with high-revenue products?
SELECT p.supplier_code,p.product_name,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.supplier_code, p.product_name ORDER BY revenue DESC;

SELECT supplier_code,SUM(s.unit_price * s.quantity) AS supplier_revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY supplier_code ORDER BY supplier_revenue DESC;

-- Identify products that sell well in one region but poorly in others.
WITH product_region_revenue AS (SELECT p.product_name,s.region,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name, s.region)
SELECT product_name,MAX(revenue) AS max_region_revenue,MIN(revenue) AS min_region_revenue,
(MAX(revenue) - MIN(revenue)) AS regional_variance FROM product_region_revenue
GROUP BY product_name ORDER BY regional_variance DESC;

-- LEVEL 5 — ADVANCED SQL (WINDOW FUNCTIONS)
-- Rank products within each category based on revenue.
WITH product_revenue AS (SELECT p.product_name,p.category,SUM(s.unit_price * s.quantity) AS revenue
FROM products p INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name, p.category)
SELECT product_name,category,revenue,RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS product_rank FROM product_revenue;

-- Identify the top 3 products per category.
WITH product_revenue AS (SELECT p.product_name,p.category,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name, p.category)
SELECT * FROM (SELECT product_name,category,revenue,RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS product_rank
FROM product_revenue) ranked WHERE product_rank <= 3;

-- Calculate cumulative revenue contribution across products.
WITH product_revenue AS (SELECT p.product_name,SUM(s.unit_price * s.quantity) AS revenue FROM products p
INNER JOIN sales s ON p.product_id = s.product_id GROUP BY p.product_name)
SELECT product_name,revenue,SUM(revenue) OVER (ORDER BY revenue DESC) AS running_revenue,
ROUND(SUM(revenue) OVER (ORDER BY revenue DESC)/SUM(revenue) OVER () * 100, 2) AS cumulative_pct FROM product_revenue;

-- For each customer, calculate:
-- Total revenue
-- Rank customers based on spending
WITH customer_revenue AS (SELECT customer_id,SUM(unit_price * quantity) AS total_revenue 
FROM sales GROUP BY customer_id)
SELECT customer_id,total_revenue,RANK() OVER (ORDER BY total_revenue DESC) AS customer_rank FROM customer_revenue;

-- Identify customers whose spending is above the average of their loyalty tier.
WITH customer_revenue AS (SELECT c.customer_id,COALESCE(c.loyalty_tier, 'Unknown') AS loyalty_tier,
SUM(s.unit_price * s.quantity) AS revenue FROM customers c 
INNER JOIN sales s ON c.customer_id = s.customer_id GROUP BY c.customer_id,COALESCE(c.loyalty_tier, 'Unknown'))
SELECT * FROM (SELECT customer_id,loyalty_tier,revenue,AVG(revenue) OVER (PARTITION BY loyalty_tier) AS avg_tier_revenue
FROM customer_revenue) t WHERE revenue > avg_tier_revenue;


-- LEVEL 6 — DATA MODELING & REUSABILITY (VIEWS, structured thinking)
-- Create a final analytics view combining sales, customer, and product data.
CREATE VIEW vw_sales_analytics AS SELECT s.order_id, s.order_date,DATE_FORMAT(s.order_date, '%Y-%m') AS order_month,
s.customer_id,COALESCE(c.loyalty_tier, 'Unknown') AS loyalty_tier,c.gender,TRIM(c.region)AS customer_region,
s.product_id,p.product_name,p.category,p.supplier_code,s.quantity,s.unit_price,s.discount_applied, 
(s.unit_price * s.quantity) AS revenue, s.delivery_status,s.payment_method FROM sales s
LEFT JOIN customers c ON s.customer_id = c.customer_id
LEFT JOIN products p ON s.product_id = p.product_id;

-- From this view, compute:
-- Monthly revenue trend
SELECT order_month, ROUND(SUM(revenue), 2) AS monthly_revenue
FROM vw_sales_analytics GROUP BY order_month ORDER BY order_month;

-- Category-wise growth
SELECT category,order_month,ROUND(SUM(revenue), 2) AS monthly_category_revenue
FROM vw_sales_analytics GROUP BY category, order_month ORDER BY category, order_month;

-- Identify seasonality or spikes in order volume.
SELECT order_month, COUNT(order_id) AS order_volume FROM vw_sales_analytics 
GROUP BY order_month ORDER BY order_volume DESC;

-- Build a query that management can reuse to monitor top customers monthly.
SELECT order_month,customer_id,ROUND(SUM(revenue), 2) AS customer_monthly_revenue FROM vw_sales_analytics
GROUP BY order_month, customer_id ORDER BY order_month, customer_monthly_revenue DESC;

-- Create a summary table showing:
-- Category
-- Total revenue
-- % contribution to overall revenue
SELECT category,ROUND(SUM(revenue), 2) AS total_revenue,
ROUND(SUM(revenue) * 100.0 / SUM(SUM(revenue)) OVER (),2) AS revenue_contribution_pct
FROM vw_sales_analytics GROUP BY category ORDER BY total_revenue DESC;


select (unit_price * quantity) * (1 - discount_applied) as discount from sales;

SELECT DISTINCT discount_applied FROM sales ORDER BY discount_applied;

SELECT SUM(unit_price * quantity) AS gross_revenue,
SUM((unit_price * quantity) * (1 - discount_applied)) AS net_revenue FROM sales;

SELECT MIN(discount_applied), MAX(discount_applied) FROM sales;



